[package]
name = "gb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.5", features = ["derive"] }
num_enum = "0.5.7"

[dev-dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "1.0.87"

